
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_v1_development
 


test:
  <<: *default
  database: api_v1_test

production:
  <<: *default
  database: api_v1_production
  username: api_v1
  password: <%= ENV['API_V1_DATABASE_PASSWORD'] %>
